import { Schema, model } from 'mongoose';
import { IPayroll, PayrollStatus, IAllowance, IDeduction } from '@/types/index.js';

const allowanceSchema = new Schema<IAllowance>(
  {
    type: {
      type: String,
      required: [true, 'Allowance type is required'],
      trim: true,
    },
    amount: {
      type: Number,
      required: [true, 'Allowance amount is required'],
      min: [0, 'Allowance amount must be positive'],
    },
    isPercentage: {
      type: Boolean,
      default: false,
    },
  },
  { _id: false }
);

const deductionSchema = new Schema<IDeduction>(
  {
    type: {
      type: String,
      required: [true, 'Deduction type is required'],
      trim: true,
    },
    amount: {
      type: Number,
      required: [true, 'Deduction amount is required'],
      min: [0, 'Deduction amount must be positive'],
    },
    isPercentage: {
      type: Boolean,
      default: false,
    },
  },
  { _id: false }
);

const payrollSchema = new Schema<IPayroll>(
  {
    userId: {
      type: Schema.Types.ObjectId as any,
      ref: 'User',
      required: [true, 'User ID is required'],
      index: true,
    },
    month: {
      type: String,
      required: [true, 'Month is required'],
      match: [/^(0[1-9]|1[0-2])$/, 'Month must be in MM format (01-12)'],
    },
    year: {
      type: Number,
      required: [true, 'Year is required'],
      min: [2000, 'Year must be 2000 or later'],
      max: [3000, 'Year must be before 3000'],
    },
    basicSalary: {
      type: Number,
      required: [true, 'Basic salary is required'],
      min: [0, 'Basic salary must be positive'],
    },
    allowances: [allowanceSchema],
    deductions: [deductionSchema],
    grossSalary: {
      type: Number,
      default: 0,
      min: [0, 'Gross salary must be positive'],
    },
    totalDeductions: {
      type: Number,
      default: 0,
      min: [0, 'Total deductions must be positive'],
    },
    netSalary: {
      type: Number,
      default: 0,
      min: [0, 'Net salary must be positive'],
    },
    payslipPdfUrl: {
      type: String,
      trim: true,
    },
    generatedBy: {
      type: Schema.Types.ObjectId as any,
      ref: 'User',
      required: [true, 'Generated by is required'],
    },
    organizationCode: {
      type: String,
      required: [true, 'Organization code is required'],
      index: true,
      trim: true,
    },
    generatedDate: {
      type: Date,
      default: Date.now,
      required: true,
    },
    status: {
      type: String,
      enum: Object.values(PayrollStatus),
      default: PayrollStatus.DRAFT,
      required: true,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Compound indexes
payrollSchema.index({ userId: 1, month: 1, year: 1 }, { unique: true });
payrollSchema.index({ organizationCode: 1 });
payrollSchema.index({ userId: 1, organizationCode: 1 });
payrollSchema.index({ status: 1 });
payrollSchema.index({ generatedDate: 1 });
payrollSchema.index({ month: 1, year: 1, organizationCode: 1 });

// Virtual for period display
payrollSchema.virtual('payPeriod').get(function (this: any) {
  const monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const monthIndex = parseInt(this.month) - 1;
  return `${monthNames[monthIndex]} ${this.year}`;
});

// Virtual for total allowances calculation
payrollSchema.virtual('totalAllowances').get(function (this: any) {
  return this.allowances.reduce((total: number, allowance: any) => {
    if (allowance.isPercentage) {
      return total + (this.basicSalary * allowance.amount / 100);
    }
    return total + allowance.amount;
  }, 0);
});

// Pre-save middleware to calculate salary components
payrollSchema.pre('save', function (this: any, next) {
  // Calculate total allowances
  const totalAllowances = this.allowances.reduce((total: number, allowance: any) => {
    if (allowance.isPercentage) {
      return total + (this.basicSalary * allowance.amount / 100);
    }
    return total + allowance.amount;
  }, 0);

  // Calculate total deductions
  this.totalDeductions = this.deductions.reduce((total: number, deduction: any) => {
    if (deduction.isPercentage) {
      return total + (this.basicSalary * deduction.amount / 100);
    }
    return total + deduction.amount;
  }, 0);

  // Calculate gross and net salary
  this.grossSalary = this.basicSalary + totalAllowances;
  this.netSalary = this.grossSalary - this.totalDeductions;

  next();
});

// Static method to generate payroll for all employees
payrollSchema.statics.generateMonthlyPayroll = async function (
  month: string,
  year: number,
  generatedBy: string
) {
  const Employee = model('Employee');
  const employees = await Employee.find({ status: 'active' });

  const payrollPromises = employees.map(async (employee: any) => {
    // Check if payroll already exists
    const existingPayroll = await this.findOne({
      userId: employee._id,
      month,
      year,
    });

    if (existingPayroll) {
      return null; // Skip if already exists
    }

    // Create payroll
    const payroll = new this({
      userId: employee._id,
      month,
      year,
      basicSalary: employee.salaryStructure.basicSalary,
      allowances: employee.salaryStructure.allowances,
      deductions: employee.salaryStructure.deductions,
      generatedBy,
    });

    return payroll.save();
  });

  const results = await Promise.allSettled(payrollPromises);
  return results.filter(result => result.status === 'fulfilled' && result.value !== null);
};

export const Payroll = model<IPayroll>('Payroll', payrollSchema);